app:
  project_name: "FinSight-AI"
  version: "1.0.0"
  debug: true

llm:
  ollama:
    base_url: "http://localhost:11434"
    model: "qwen2.5:7b"
    vlm_model: "qwen2.5vl:7b"
    embed_model: "nomic-embed-text"

rag:
  # EMBEDDING
  embedding:
    ollama: "nomic-embed-text"

  # RETRIEVAL
  retrieval:
    dense:
      enabled: true
      similarity_top_k: 15

    sparse:
      enabled: true
      type: "bm25"
      similarity_top_k: 15

  # RERANKER
  reranker:
    enabled: true
    model: "BAAI/bge-reranker-v2-m3"
    top_n: 3

  # CHUNKING
  chunking:
    parent:
      chunk_size: 2000
      chunk_overlap: 200

    child:
      chunk_size: 200
      chunk_overlap: 50

storage:
  storage_dir: "storage/"

  # VECTOR DATABASE
  vector_store:
    qdrant:
      mode: "local"
      vector_db_dir: "storage/vector_db"
      collection_name: "finsight_collection"
      vector_size: 768
      distance: "cosine"

  # MEMORY
  memory:
    qdrant:
      memory_dir: "storage/memory_db"
      mode: "local"
      path: "storage/memory"
      history_collection: "chat_history"

  # DATA
  data:
    data_dir: "data"
    raw_dir: "data/raw"
    processed_dir: "data/processed"

  # RELATIONAL DATABASE
  database:
    url: "sqlite:///./storage/app_db.sqlite"
    echo: false

# OBSERVABILITY
langsmith:
  enabled: false
  project: "finsight_ai_monitor"
  endpoint: "https://api.smith.langchain.com"
